### PR TITLE
Add support for ISK

### PR DESCRIPTION
**Pull request by orjhor**
This will make it possible to pay with Icelandic Króna.

### CODE REVIEW

**Comment by syntaxerror** [comment]
Shouldn't the minor units of ISK be 2?
And thus it's already supported in that get_currency_minorunits function?
`        if ( array_key_exists( $currency_code, $currency_minorunits ) ) {
            return $currency_minorunits[ $currency_code ];
        } else {
            return 2;
        }`

**Comment by orjhor** [comment]
@syntaxerror Not according to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217). We were not able to take payments via this plugin until adding this fix.

**Comment by syntaxerror** [comment]
OK, wonder if it has changed, or if Bambora (ePay) always had it wrong then.
Anyhow Bambora also would need to look at their old docs then: http://epay.bambora.com/en/currency-codes

**Comment by AllanWLie** [comment]
Hi @orjhor 
Thank you for your pull request. It have been merged into master and will be part of the next release. 

@syntaxerror You are correct in relation to the ePay module for Woocommerce. Here ISK should be defined with two minor units. 
Back in the 90's ISK was using two minor units, this have changed to zero minor units. But Visa and MasterCard is still going by the old minor units. The Checkout platform is for Visa and MasterCard is handling the conversion according to the scheme specifications.  
The old ePay platform do not have this functionality so it is required to use two minor units for ISK

**Comment by syntaxerror** [comment]
Ah, I see @AllanWLie. But then, could it be a good idea to expand the docs for Checkout at Bambora Developer, as this is the only currency table/info about supported currencies coming up if googling 'bambora currency'? If all currencies are supported it can simply be stated, with a link to the ISO 4217 Wikipage, just so it's clear there is a difference between your platforms. And btw, it would also be great to have a internal search feature for the Bambora Developer page, making it easier to find specific terms and features. :)

**Comment by AllanWLie** [comment]
@syntaxerror 
Both your requests have been added as feature requests. 

Have a good day.

**Pull request merged**
