### PR TITLE
Better PSP reference. Wrongly spelled custommer

### PR DESCRIPTION
**Pull request by jonathan-dejong**
I've changed the PSP reference to be unique for bambora and adhere to coding standards for meta keys. This avoids potential issues further along the line. 

Also renamed all mentions of custommer to customer.

### CODE REVIEW

**Comment by jonathan-dejong** [comment]
Also fixed an instance where the constant PSP_REFERENCE was not being used in the code but rather a direct reference to "Transaction ID".

**Comment by jonathan-dejong** [comment]
Also fixed an instance where the constant PSP_REFERENCE was not being used in the code but rather a direct reference to "Transaction ID".

**Comment by AllanWLie** [comment]
We cant just change the PSP reference, since it will breake for already saved meta. Another fix is done in the newest release here: https://github.com/bambora/checkout-woocommerce/releases/latest

**Comment by jonathan-dejong** [comment]
lol, was not thinking that far ahead xD

**Pull request closed without merging**
